---
abstract: 'send Log::Any logs to syslog'
author:
  - 'Daniel Pittman <daniel@rimspace.net>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter-Syslog
recommends: {}
requires:
  File::Basename: 0
  Log::Any::Adapter::Base: 0
  Log::Any::Adapter::Util: 0
  Unix::Syslog: 0
version: 1.0
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::BumpVersionFromGit
      name: '@DANIELP/BumpVersionFromGit'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DANIELP/GatherDir'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DANIELP/ExecDir'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DANIELP/ShareDir'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DANIELP/PruneCruft'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DANIELP/ManifestSkip'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@DANIELP/AutoPrereq'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DANIELP/PkgVersion'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@DANIELP/PodVersion'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@DANIELP/ReportVersions'
      version: 1.100880
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@DANIELP/CompileTests'
      version: 1.100220
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@DANIELP/HasVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@DANIELP/MetaTests'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@DANIELP/MinimumVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@DANIELP/PortabilityTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::SynopsisTests
      name: '@DANIELP/SynopsisTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DANIELP/PodSyntaxTests'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@DANIELP/ExtraTests'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DANIELP/MetaConfig'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DANIELP/MetaYAML'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DANIELP/MetaJSON'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::License
      name: '@DANIELP/License'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DANIELP/Readme'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DANIELP/MakeMaker'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@DANIELP/ChangelogFromGit'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DANIELP/Manifest'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DANIELP/Git::Check'
      version: 1.100760
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DANIELP/TestRelease'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DANIELP/ConfirmRelease'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@DANIELP/Git::Commit'
      version: 1.100760
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DANIELP/Git::Tag'
      version: 1.100760
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DANIELP/UploadToCPAN'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 2.101040
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 2.101040
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 2.101040
